name: Build Test

on:
  push:
    branches:
      - master
      - 'mamoru*'
      - develop


  pull_request:
    branches:
      - master
      - 'mamoru*'
      - develop


jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go version

      - name: Cache Go modules and build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup SSH for Private Repository Access
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MAMORU_ETHERMINT_SSH_PRIVATE_KEY }}

      - name: Test and Build with Makefile
        run: |
          export GOPRIVATE=github.com/Mamoru-Foundation/*
          go mod download
          make build
