name: "Build docker image"
on:
  push:
    branches:
      - master
      - 'mamoru*'
      - develop

env:
  REPOSITORY: mamorufoundation/kava-sniffer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%d')"

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MAMORU_ETHERMINT_SSH_PRIVATE_KEY }}

      - name: Prepare git and ssh config for build context
        run: |
          mkdir -p root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            GIT_REVISION=${{ github.sha }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            PROFILE=release
            COMMIT=${{ github.sha }}
          push: true
          tags: |
            ${{ env.REPOSITORY }}:latest
            ${{ env.REPOSITORY }}:${{ github.sha }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
